steps:
  - name: gcr.io/cloud-builders/docker
    id: pull-build-cache
    args: [pull, '${_CACHE_IMAGE}']
    allowFailure: true
  - name: gcr.io/cloud-builders/docker
    id: build-runtime
    args:
      - build
      - --cache-from=${_CACHE_IMAGE}
      - --file=infra/runtime/Dockerfile
      - --build-arg=CODE_VERSION=${_VERSION}
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/commerce/runtime:${_VERSION}
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/commerce/runtime:${_VERSION}
options:
  logging: GCS_ONLY
logsBucket: gs://commerce-agents-dev-builds
timeout: 1200s
substitutions:
  _REGION: us-central1
  _VERSION: dev
  _CACHE_IMAGE: us-central1-docker.pkg.dev/commerce-agents-dev/commerce/runtime@sha256:8ce26d515029a08c1edf84a0da8df96041cff790aa6440a4dc1e70af0278c126
