version: 2
models:
  - name: stg_klaviyo__events
    columns:
      - name: event_key
        data_tests: [not_null, unique]
      - name: event_id
        data_tests: [not_null]
      - name: metric_id
        data_tests: [not_null]
      - name: unknown_metric_id
        data_tests: [not_null]
      - name: shop_key
        data_tests: [not_null]
      - name: extraction_id
        data_tests: [not_null]
      - name: published_at
        data_tests: [not_null]
