#!/usr/bin/env python3
"""Generate the Cube data model from the serving contract (single source of truth).

`cube/model/` is GENERATED from `semantic/serving_contract.yaml` (+ the catalog in
`semantic/metrics.yaml` for descriptions). Do not hand-edit `cube/model/`; edit the
serving contract and re-run this script. This kills the drift between the contract,
the marts and the cube model (each metric is defined once, in the contract).

Rules mirrored from the contract / cube README:
  - Business math lives in the dbt marts. Cubes only route columns + roll up.
  - `base` metrics -> one `sum` measure over the mart's value_column.
  - `derived` metrics -> ratio-of-sums over other measures ({num}/NULLIF({den},0)).
  - `blocked` metrics -> emitted as `public: false` measures (kept for reconcile),
    never exposed in a view (no one can query a 0/NULL-by-design number).
  - Only servable metrics (target_validated / sql_template) reach the public view.
  - Tenant/extraction columns are dimensions but `public: false` (scoping is
    server-side via securityContext, never chosen by the caller).

Usage:
    python scripts/generate_cube_model.py            # write cube/model/
    python scripts/generate_cube_model.py --check    # fail if output is stale (CI)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
CONTRACT = REPO / "semantic" / "serving_contract.yaml"
CATALOG = REPO / "semantic" / "metrics.yaml"
OUT_CUBES = REPO / "cube" / "model" / "cubes"
OUT_VIEWS = REPO / "cube" / "model" / "views"

SERVABLE = {"target_validated", "sql_template"}
HEADER = (
    "# GENERATED by scripts/generate_cube_model.py from semantic/serving_contract.yaml\n"
    "# DO NOT EDIT BY HAND — edit the serving contract and re-run the generator.\n"
)


def is_currency_base(metric: dict) -> bool:
    vc = metric.get("value_column", "")
    return vc.endswith("_amount") or metric.get("basis") in {"gmv", "nmv"}


def describe(name: str, metric: dict, catalog: dict) -> str:
    parts = []
    cat = catalog.get(name)
    if cat and cat.get("definition"):
        parts.append(cat["definition"].strip().rstrip("."))
    for flag in metric.get("honesty_flags", []) or []:
        parts.append(flag.strip())
    if metric.get("blocked_reason"):
        parts.append(f"BLOCKED: {metric['blocked_reason'].strip()}")
    if metric.get("sign_convention") == "stored_negative":
        parts.append("Stored negative; nets into NMV — do not subtract twice.")
    return ". ".join(parts)


def yq(s: str) -> str:
    """Quote a YAML scalar for a double-quoted description value."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_cube(mart_name: str, mart: dict, contract: dict, catalog: dict) -> tuple[str, str, str, list[str]]:
    """Return (cube_name, view_name, cube_yaml, servable_measure_names)."""
    metrics = contract["metrics"]
    defaults = contract.get("defaults", {})
    tenant = defaults.get("tenant_column", "shop_key")
    extraction = defaults.get("extraction_column", "extraction_id")

    cube_name = mart.get("cube_name", mart_name.replace("metric_", ""))
    view_name = mart.get("view_name", cube_name)
    sql_table = f"{mart['dataset']}.{mart_name}"

    # base metrics on this mart, in contract order
    base = [(n, m) for n, m in metrics.items()
            if m.get("kind") == "base" and m.get("source_mart") == mart_name]
    base_names = {n for n, _ in base}
    currency = {n: is_currency_base(m) for n, m in base}
    # derived metrics whose numerator resolves to this mart
    derived = [(n, m) for n, m in metrics.items()
               if m.get("kind") == "derived" and m.get("numerator") in base_names]

    lines: list[str] = [HEADER, "cubes:", f"  - name: {cube_name}",
                        f"    sql_table: {sql_table}", ""]

    # ---- dimensions ----
    lines.append("    dimensions:")
    lines.append(f"      - name: {tenant}       # tenant key — scoping is server-side")
    lines.append(f"        sql: {tenant}")
    lines.append("        type: string")
    lines.append("        public: false")
    lines.append(f"      - name: {extraction}")
    lines.append(f"        sql: {extraction}")
    lines.append("        type: string")
    lines.append("        public: false")
    for dim in mart.get("dimensions", []):
        lines.append(f"      - name: {dim}")
        lines.append(f"        sql: {dim}")
        lines.append("        type: string")
    tcol = mart["time_column"]
    lines.append(f"      - name: {tcol}")
    lines.append(f"        sql: {tcol}")
    lines.append("        type: time")
    lines.append("")

    # ---- measures ----
    servable_measures: list[str] = []
    lines.append("    measures:")
    lines.append("      # --- base (additive), from the mart ---")
    for name, m in base:
        blocked = m.get("implementation_status") == "blocked"
        lines.append(f"      - name: {name}")
        lines.append(f"        sql: {m['value_column']}")
        lines.append(f"        type: {m.get('aggregation', 'sum')}")
        if currency[name]:
            lines.append("        format: currency")
        if blocked:
            lines.append("        public: false")
        desc = describe(name, m, catalog)
        if desc:
            lines.append(f"        description: {yq(desc)}")
        if not blocked and m.get("implementation_status") in SERVABLE:
            servable_measures.append(name)
    if derived:
        lines.append("      # --- derived (ratio-of-sums; computed, not stored) ---")
    for name, m in derived:
        num, den = m["numerator"], m["denominator"]
        num_cur = currency.get(num, False)
        den_cur = currency.get(den, False)
        lines.append(f"      - name: {name}")
        lines.append(f'        sql: "{{{num}}} / NULLIF({{{den}}}, 0)"')
        lines.append("        type: number")
        if num_cur and not den_cur:
            lines.append("        format: currency")
        desc = describe(name, m, catalog)
        if desc:
            lines.append(f"        description: {yq(desc)}")
        if m.get("implementation_status") in SERVABLE:
            servable_measures.append(name)

    # ---- pre-aggregation (only for validated marts) ----
    roll = [n for n, m in base
            if m.get("implementation_status") == "target_validated"]
    if roll:
        lines.append("")
        lines.append("    pre_aggregations:")
        lines.append("      - name: daily_rollup")
        lines.append("        measures:")
        for n in roll:
            lines.append(f"          - {n}")
        lines.append("        dimensions:")
        lines.append(f"          - {tenant}")
        for dim in mart.get("dimensions", []):
            lines.append(f"          - {dim}")
        lines.append(f"        time_dimension: {tcol}")
        lines.append(f"        granularity: {mart.get('grain', 'day')}")
        lines.append("        refresh_key:")
        lines.append(f"          sql: SELECT MAX(computed_at) FROM {sql_table}")

    return cube_name, view_name, "\n".join(lines) + "\n", servable_measures


def build_view(view_name: str, cube_name: str, mart: dict, servable: list[str]) -> str:
    tcol = mart["time_column"]
    lines = [HEADER, "views:", f"  - name: {view_name}",
             "    public: true",
             f'    description: "Servable {cube_name} metrics by {mart.get("grain", "day")}."',
             "    cubes:",
             f"      - join_path: {cube_name}",
             "        includes:",
             f"          - {tcol}"]
    for dim in mart.get("dimensions", []):
        lines.append(f"          - {dim}")
    for name in servable:
        lines.append(f"          - {name}")
    return "\n".join(lines) + "\n"


def generate() -> dict[str, str]:
    contract = yaml.safe_load(CONTRACT.read_text())
    catalog = (yaml.safe_load(CATALOG.read_text()) or {}).get("metrics", {})
    files: dict[str, str] = {}
    for mart_name, mart in contract.get("marts", {}).items():
        cube_name, view_name, cube_yaml, servable = build_cube(mart_name, mart, contract, catalog)
        files[str(OUT_CUBES / f"{cube_name}.yml")] = cube_yaml
        files[str(OUT_VIEWS / f"{view_name}.yml")] = build_view(view_name, cube_name, mart, servable)
    return files


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if cube/model/ is stale (for CI)")
    args = ap.parse_args()

    files = generate()
    if args.check:
        stale = [p for p, c in files.items()
                 if not Path(p).exists() or Path(p).read_text() != c]
        if stale:
            print("STALE (re-run scripts/generate_cube_model.py):")
            for p in stale:
                print("  ", Path(p).relative_to(REPO))
            return 1
        print("cube/model/ is up to date with the serving contract.")
        return 0

    OUT_CUBES.mkdir(parents=True, exist_ok=True)
    OUT_VIEWS.mkdir(parents=True, exist_ok=True)
    for p, c in files.items():
        Path(p).write_text(c)
        print("wrote", Path(p).relative_to(REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
